---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nginx-demo
  name: nginx-demo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: nginx-demo
  type: LoadBalancer